// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/components/ComTest":{"path":"components/com-test","id":"docs/components/ComTest","parentId":"DocLayout"},"docs/guide":{"path":"guide","id":"docs/guide","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout","prerender":false}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__404" */'/Users/xg-a06/g/tpl-lib-ts/node_modules/.pnpm/dumi@2.2.16_@babel+core@7.23.6_@types+node@20.10.5_@types+react@18.2.45_eslint@8.56.0_prettie_4bxdu7277yib77rac4dnmzbfxq/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp-production__dumi__theme__ContextWrapper" */'/Users/xg-a06/g/tpl-lib-ts/.dumi/tmp-production/dumi/theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__dumi__theme-default__layouts__DocLayout__index" */'/Users/xg-a06/g/tpl-lib-ts/node_modules/.pnpm/dumi@2.2.16_@babel+core@7.23.6_@types+node@20.10.5_@types+react@18.2.45_eslint@8.56.0_prettie_4bxdu7277yib77rac4dnmzbfxq/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'docs/components/ComTest': React.lazy(() => import(/* webpackChunkName: "docs__components__ComTest.md" */'/Users/xg-a06/g/tpl-lib-ts/docs/components/ComTest.md')),
'docs/guide': React.lazy(() => import(/* webpackChunkName: "docs__guide.md" */'/Users/xg-a06/g/tpl-lib-ts/docs/guide.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/xg-a06/g/tpl-lib-ts/docs/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__dumi__dist__client__pages__Demo__index" */'/Users/xg-a06/g/tpl-lib-ts/node_modules/.pnpm/dumi@2.2.16_@babel+core@7.23.6_@types+node@20.10.5_@types+react@18.2.45_eslint@8.56.0_prettie_4bxdu7277yib77rac4dnmzbfxq/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
