// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';
import { SiteContext } from '/Users/xg-a06/g/tpl-lib-ts/node_modules/.pnpm/dumi@2.2.16_@babel+core@7.23.6_@types+node@20.10.5_@types+react@18.2.45_eslint@8.56.0_prettie_4bxdu7277yib77rac4dnmzbfxq/node_modules/dumi/dist/client/theme-api/context.js';
import { demos, components } from '../meta';
import { locales } from '../locales/config';

const entryExports = {
  
  
};

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(false);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider value={{
      pkg: {"name":"tpl-lib-ts","description":"library typescript template","version":"1.0.0","license":"MIT","author":"enforcer.a06@gmail.com"},
      historyType: "browser",
      entryExports,
      demos,
      components,
      locales,
      loading,
      setLoading,
      hostname: undefined,
      themeConfig: {"footer":"Copyright © 2023 | Powered by Enforcer-Squad","prefersColor":{"default":"light","switch":true},"nprogress":true,"lastUpdated":true,"name":"","favicons":"/favicon.ico","logo":"/logo.png","socialLinks":{"github":"https://github.com/enforcer-squad"}},
      _2_level_nav_available: true,
    }}>
      {outlet}
    </SiteContext.Provider>
  );
}
