// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/xg-a06/g/tpl-lib-ts/node_modules/.pnpm/dumi@2.2.16_@babel+core@7.23.6_@types+node@20.10.5_@types+react@18.2.45_eslint@8.56.0_prettie_4bxdu7277yib77rac4dnmzbfxq/node_modules/dumi/theme-default/slots/Hero/index.js';
